from sqlalchemy import Column, String, Text, Integer, Boolean
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from enum import Enum

class QuestionType(str, Enum):
    TECHNICAL = "technical"
    BEHAVIORAL = "behavioral" 
    SITUATIONAL = "situational"
    CAREER_DEVELOPMENT = "career_development"
    PERFORMANCE = "performance"
    LEADERSHIP = "leadership"
    COMMUNICATION = "communication"

class QuestionCategory(str, Enum):
    SKILLS_ASSESSMENT = "skills_assessment"
    CULTURE_FIT = "culture_fit"
    GOAL_SETTING = "goal_setting"
    FEEDBACK = "feedback"
    DEVELOPMENT = "development"

class DifficultyLevel(str, Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    EXPERT = "expert"

class QuestionDB(Base):
    __tablename__ = "questions"
    
    id = Column(String, primary_key=True)
    question_text = Column(Text, nullable=False)
    question_type = Column(String, nullable=False)
    category = Column(String, nullable=False)
    difficulty = Column(String, default=DifficultyLevel.INTERMEDIATE)
    target_positions = Column(JSON, default=list)  # List of positions this applies to
    target_departments = Column(JSON, default=list)
    target_levels = Column(JSON, default=list)
    is_active = Column(Boolean, default=True)
    weight = Column(Integer, default=1)  # Importance weight for scoring

class Question(BaseModel):
    """Question model for AI agents"""
    id: str
    question_text: str
    question_type: QuestionType
    category: QuestionCategory
    difficulty: DifficultyLevel
    target_positions: List[str] = []
    target_departments: List[str] = []
    target_levels: List[str] = []
    context: Optional[str] = None  # Additional context for the question
    expected_elements: Optional[List[str]] = None  # What we expect in a good answer

class GeneratedQuestion(BaseModel):
    """Question generated by AI agent"""
    question_text: str
    question_type: QuestionType
    category: QuestionCategory
    rationale: str  # Why this question was chosen
    weight: int = 1
    follow_up_questions: Optional[List[str]] = None
